### ISSUE TITLE
NEI issues in 1 .7.10

### ISSUE THREAD

**Issue by rikai** [MinecraftModArchive/Dendrology#38]
Have Ancient Trees on 1.7.10 and i am getting the following errors in relation to NEI:

	[06:12:43] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting com.scottkillen.mod.dendrology.item.ModSlabItem@43bacccd:5 ModSlabItem
	java.lang.IndexOutOfBoundsException: index (5) must be less than size (5)
		at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:313) ~[guava-17.0.jar:?]
		at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:295) ~[guava-17.0.jar:?]
		at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65) ~[guava-17.0.jar:?]
		at com.scottkillen.mod.koresample.common.block.SlabBlock.func_149691_a(SlabBlock.java:59) ~[SlabBlock.class:?]
		at net.minecraft.item.ItemSlab.func_77617_a(SourceFile:27) ~[aeg.class:?]
		at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
		at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
		at codechicken.nei.ItemList$1.execute(ItemList.java:205) [ItemList$1.class:?]
		at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
	[06:12:43] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting com.scottkillen.mod.dendrology.item.ModSlabItem@43bacccd:6 ModSlabItem
	java.lang.IndexOutOfBoundsException: index (6) must be less than size (5)
		at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:313) ~[guava-17.0.jar:?]
		at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:295) ~[guava-17.0.jar:?]
		at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65) ~[guava-17.0.jar:?]
		at com.scottkillen.mod.koresample.common.block.SlabBlock.func_149691_a(SlabBlock.java:59) ~[SlabBlock.class:?]
		at net.minecraft.item.ItemSlab.func_77617_a(SourceFile:27) ~[aeg.class:?]
		at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
		at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
		at codechicken.nei.ItemList$1.execute(ItemList.java:205) [ItemList$1.class:?]
		at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
	[06:12:43] [NEI Item Loading/ERROR] [NotEnoughItems]: Ommiting com.scottkillen.mod.dendrology.item.ModSlabItem@43bacccd:7 ModSlabItem
	java.lang.IndexOutOfBoundsException: index (7) must be less than size (5)
		at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:313) ~[guava-17.0.jar:?]
		at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:295) ~[guava-17.0.jar:?]
		at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65) ~[guava-17.0.jar:?]
		at com.scottkillen.mod.koresample.common.block.SlabBlock.func_149691_a(SlabBlock.java:59) ~[SlabBlock.class:?]
		at net.minecraft.item.ItemSlab.func_77617_a(SourceFile:27) ~[aeg.class:?]
		at net.minecraft.item.Item.func_77650_f(Item.java:440) ~[adb.class:?]
		at codechicken.nei.ItemList$1.damageSearch(ItemList.java:165) [ItemList$1.class:?]
		at codechicken.nei.ItemList$1.execute(ItemList.java:205) [ItemList$1.class:?]
		at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]

**Comment by ScottKillen** [comment]
Please update to the [latest version] (https://github.com/MinecraftModArchive/Dendrology/releases/latest). This was "fixed" in 1.6.2. (It isn't really a bug...just NEI spouting off unnecessarily.)
